In [1]:
import pandas as pd
df=pd.read_json("financial_practice_25_records.json")
df

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [3]:
df.head()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card

In [4]:
df.tail()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [5]:
df.isnull().sum()

Transaction_ID    0
Date              0
Customer          0
Product           0
Category          0
Quantity          0
Sales_Amount      0
Profit            0
Payment_Mode      0
dtype: int64

In [6]:
df["Profit"]=df["Profit"].ffill()

In [9]:
df["Sales_Amount"]=df["Sales_Amount"].bfill()

In [11]:
df["Quantity"]=df["Quantity"].ffill()

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Profit"].mean()
df["Profit"].median()
df["Profit"].mode()

0    7000
Name: Profit, dtype: int64

In [14]:
df

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [15]:
df["Sales_Amount"].mean()
df["Sales_Amount"].median()
df["Sales_Amount"].mode()

0      4000
1      4500
2      5000
3      7500
4      8000
5      9000
6     18000
7     20000
8     22000
9     28000
10    29000
11    30000
12    32000
13    34000
14    35000
15    36000
16    38000
17    42000
18    45000
19    46000
20    48000
21    55000
22    60000
23    70000
24    90000
Name: Sales_Amount, dtype: int64

In [16]:
df

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [17]:
df["Quantity"].mean()
df["Quantity"].median()
df["Quantity"].mode()

0    2
Name: Quantity, dtype: int64

In [18]:
df

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [19]:
df["Category"]=df["Category"].str.strip().str.title()