In [31]:
import pandas as pd

In [32]:
df=pd.read_csv("StudentsPerformance.csv")

In [33]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [34]:
df.shape

(1000, 8)

In [35]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [36]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [37]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [39]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
categorical_cols=["gender","race/ethnicity","parental level of education","lunch","test preparation course"]

In [42]:
categorical_cols

['gender',
 'race/ethnicity',
 'parental level of education',
 'lunch',
 'test preparation course']

In [43]:
for cols in categorical_cols:
    df[cols]=df[cols].astype(str).str.strip().str.lower()

In [44]:
df[cols]

0           none
1      completed
2           none
3           none
4           none
         ...
995    completed
996         none
997    completed
998    completed
999         none
Name: test preparation course, Length: 1000, dtype: object

In [45]:
score_cols=["math score","reading score","writing score"]

In [46]:
score_cols

['math score', 'reading score', 'writing score']

In [47]:
score_cols=["math score","reading score","writing score"]	
for cols in score_cols:
    mean=df[cols].mean()
    print("mean score:",mean)
    mode=df[cols].mode()
    print("mean score:",mode)
    median=df[cols].median()
    print("median score:",median)

mean score: 66.089
mean score: 0    65
Name: math score, dtype: int64
median score: 66.0
mean score: 69.169
mean score: 0    72
Name: reading score, dtype: int64
median score: 70.0
mean score: 68.054
mean score: 0    74
Name: writing score, dtype: int64
median score: 69.0

In [48]:
for cols in score_cols:
    mean=df[cols].mean()
    median=df[cols].median()
    mode=df[cols].mode()
    std=df[cols].std()
    Q1=df[cols].quantile(0.25)
    Q3=df[cols].quantile(0.75)
    print("mean:",mean)
    print("median:",median)
    print("mode:",mode)
    print("std:",std)
    print("Q1:",Q1)
    print("Q3:",Q3)

mean: 66.089
median: 66.0
mode: 0    65
Name: math score, dtype: int64
std: 15.163080096009468
Q1: 57.0
Q3: 77.0
mean: 69.169
median: 70.0
mode: 0    72
Name: reading score, dtype: int64
std: 14.60019193725222
Q1: 59.0
Q3: 79.0
mean: 68.054
median: 69.0
mode: 0    74
Name: writing score, dtype: int64
std: 15.195657010869642
Q1: 57.75
Q3: 79.0

In [49]:
print(df[score_cols].describe())

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [50]:
df["Total Marks"]=df[score_cols].sum(axis=1)

In [51]:
df["Percentage"]=(df["Total Marks"]/300)*100

In [52]:
print(df[score_cols+["Total Marks","Percentage"]])

     math score  reading score  writing score  Total Marks  Percentage
0            72             72             74          218   72.666667
1            69             90             88          247   82.333333
2            90             95             93          278   92.666667
3            47             57             44          148   49.333333
4            76             78             75          229   76.333333
..          ...            ...            ...          ...         ...
995          88             99             95          282   94.000000
996          62             55             55          172   57.333333
997          59             71             65          195   65.000000
998          68             78             77          223   74.333333
999          77             86             86          249   83.000000

[1000 rows x 5 columns]

In [53]:
performance=[]
for percentage in df["Percentage"]:
    if percentage >=90:
        performance.append("Excellent")
    elif percentage >=75:
        performance.append("Very Good")
    elif percentage >=60:
        performance.append("Good")   
    elif percentage >=50:
        performance.append("Average")
    else:
         performance.append("Need a Improvement")
df["Performance"]=performance
print(df[["Percentage","Performance"]])

     Percentage         Performance
0     72.666667                Good
1     82.333333           Very Good
2     92.666667           Excellent
3     49.333333  Need a Improvement
4     76.333333           Very Good
..          ...                 ...
995   94.000000           Excellent
996   57.333333             Average
997   65.000000                Good
998   74.333333                Good
999   83.000000           Very Good

[1000 rows x 2 columns]

In [55]:
for col in ["math score","reading score","writing score"]:
    Q1=df[col].quantile(0.25)
    Q2=df[col].quantile(0.75)

    IQR=Q3-Q1

    lower=Q1-1.5*IQR
    upper=Q3-1.5*IQR

    outliers=df[
        (df[col]<lower)|
        (df[col]>upper)
        ]
    print(outliers[col])

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 910, dtype: int64
0      72
1      90
2      95
3      57
4      78
       ..
995    99
996    55
997    71
998    78
999    86
Name: reading score, Length: 916, dtype: int64
0      74
1      88
2      93
4      75
5      78
       ..
995    95
996    55
997    65
998    77
999    86
Name: writing score, Length: 908, dtype: int64