In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("stock_data_50_records.csv")

In [5]:
df

          Date    Open    High     Low   Close    Volume
0   2026-01-02  101.09  103.37  100.08  102.04   89377.0
1   2026-01-05  101.05  101.99   99.91  100.58   88404.0
2   2026-01-06  102.41  103.15   99.47  101.36   94045.0
3   2026-01-07  105.35  108.05  103.53  106.87   72352.0
4   2026-01-08  105.13  109.88  104.24  107.49   79790.0
5   2026-01-09  104.91  108.22  103.42  107.07   81919.0
6   2026-01-12  107.95  109.49  104.84  106.57   45600.0
7   2026-01-13  109.53  111.44  107.88     NaN   69124.0
8   2026-01-14  108.89  111.08  107.60  109.85   67643.0
9   2026-01-15  110.07  114.76  109.21  112.32   80764.0
10  2026-01-16  109.43  111.85  108.13  108.77   49007.0
11  2026-01-19  108.79  109.79  106.87  108.72  450000.0
12  2026-01-20  109.43  110.92  105.67  107.52   96835.0
13  2026-01-21  106.18  107.28  102.64  104.09   77410.0
14  2026-01-22  103.28  106.28  102.27  105.21   84080.0
15  2026-01-23  102.47  106.05  101.45  105.48   80447.0
16  2026-01-26  100.84  102.72   99.25  101.00   48208.0
17  2026-01-27  101.61  105.43   99.76  103.92   96491.0
18  2026-01-28  100.18  101.80   98.35  101.20       NaN
19  2026-01-29   97.83   98.89   95.17   96.84   58589.0
20  2026-01-09  104.91  108.22  103.42  107.07   81919.0
21  2026-02-02  100.47  104.83   99.84  103.85   57453.0
22  2026-02-03  100.79  101.81  100.05  101.02   76212.0
23  2026-02-04   98.42  103.33   96.57  101.85   83525.0
24  2026-02-05   97.64  100.11   91.29   92.70   87202.0
25  2026-02-06   98.04  100.96   97.53   99.98   72635.0
26  2026-02-09   96.17   98.48   95.52   96.64   73828.0
27  2026-02-10   97.05   99.07   95.25   96.75  620000.0
28  2026-02-11   96.17   97.63   95.66   96.65   43420.0
29  2026-02-12   95.84   97.80   91.42   92.16   71216.0
30  2026-02-13   94.96   96.20   93.50   94.82   40301.0
31  2026-02-16   98.49  101.26   96.95   99.50   85236.0
32  2026-02-17   98.67     NaN   97.19  101.93   89758.0
33  2026-02-18   96.96   98.53   95.38   96.22   92322.0
34  2026-02-19   98.64   99.32   95.75   97.32   40699.0
35  2026-01-22  103.28  106.28  102.27  105.21   84080.0
36  2026-02-23   97.22  100.49   96.23   99.35   98483.0
37  2026-02-24   93.89   95.72   92.27   94.85   40190.0
38  2026-02-25   91.70   92.28   89.47   90.94   50492.0
39  2026-02-26   92.26   95.27   90.49   93.59   90132.0
40  2026-02-27   93.79   96.14   92.30   94.28   75743.0
41  2026-03-02   94.30   97.07   92.95   96.54  850000.0
42  2026-03-03   94.29   95.81   92.55   93.19   90336.0
43  2026-03-04   93.95   94.90   92.54   93.59   92479.0
44  2026-03-05     NaN   93.27   90.10   91.00   59778.0
45  2026-03-06   90.39   91.24   86.89   87.76   97471.0
46  2026-03-09   89.76   92.53   87.80   90.65   66641.0
47  2026-02-06   98.04  100.96   97.53   99.98   72635.0
48  2026-03-11   92.68   95.36   90.84   92.99   72745.0
49  2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [6]:
df.head()

         Date    Open    High     Low   Close   Volume
0  2026-01-02  101.09  103.37  100.08  102.04  89377.0
1  2026-01-05  101.05  101.99   99.91  100.58  88404.0
2  2026-01-06  102.41  103.15   99.47  101.36  94045.0
3  2026-01-07  105.35  108.05  103.53  106.87  72352.0
4  2026-01-08  105.13  109.88  104.24  107.49  79790.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Open    49 non-null     float64
 2   High    49 non-null     float64
 3   Low     50 non-null     float64
 4   Close   49 non-null     float64
 5   Volume  49 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

In [8]:
df["Date"]= pd.to_datetime(df["Date"])

In [9]:
df.dtypes

Date      datetime64[ns]
Open             float64
High             float64
Low              float64
Close            float64
Volume           float64
dtype: object

In [10]:
df.isnull().sum()

Date      0
Open      1
High      1
Low       0
Close     1
Volume    1
dtype: int64

In [11]:
df=df.dropna()

In [12]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(3)

In [14]:
df.drop_duplicates().sum()

TypeError: 'DatetimeArray' with dtype datetime64[ns] does not support reduction 'sum'

In [16]:
df["Price_Delta"]=df["Close"]-df["Open"]

C:\Users\Dell\AppData\Local\Temp\ipykernel_15228\3497891096.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price_Delta"]=df["Close"]-df["Open"]

In [17]:
df

         Date    Open    High     Low   Close    Volume  Price_Delta
0  2026-01-02  101.09  103.37  100.08  102.04   89377.0         0.95
1  2026-01-05  101.05  101.99   99.91  100.58   88404.0        -0.47
2  2026-01-06  102.41  103.15   99.47  101.36   94045.0        -1.05
3  2026-01-07  105.35  108.05  103.53  106.87   72352.0         1.52
4  2026-01-08  105.13  109.88  104.24  107.49   79790.0         2.36
5  2026-01-09  104.91  108.22  103.42  107.07   81919.0         2.16
6  2026-01-12  107.95  109.49  104.84  106.57   45600.0        -1.38
8  2026-01-14  108.89  111.08  107.60  109.85   67643.0         0.96
9  2026-01-15  110.07  114.76  109.21  112.32   80764.0         2.25
10 2026-01-16  109.43  111.85  108.13  108.77   49007.0        -0.66
11 2026-01-19  108.79  109.79  106.87  108.72  450000.0        -0.07
12 2026-01-20  109.43  110.92  105.67  107.52   96835.0        -1.91
13 2026-01-21  106.18  107.28  102.64  104.09   77410.0        -2.09
14 2026-01-22  103.28  106.28  102.27  105.21   84080.0         1.93
15 2026-01-23  102.47  106.05  101.45  105.48   80447.0         3.01
16 2026-01-26  100.84  102.72   99.25  101.00   48208.0         0.16
17 2026-01-27  101.61  105.43   99.76  103.92   96491.0         2.31
19 2026-01-29   97.83   98.89   95.17   96.84   58589.0        -0.99
20 2026-01-09  104.91  108.22  103.42  107.07   81919.0         2.16
21 2026-02-02  100.47  104.83   99.84  103.85   57453.0         3.38
22 2026-02-03  100.79  101.81  100.05  101.02   76212.0         0.23
23 2026-02-04   98.42  103.33   96.57  101.85   83525.0         3.43
24 2026-02-05   97.64  100.11   91.29   92.70   87202.0        -4.94
25 2026-02-06   98.04  100.96   97.53   99.98   72635.0         1.94
26 2026-02-09   96.17   98.48   95.52   96.64   73828.0         0.47
27 2026-02-10   97.05   99.07   95.25   96.75  620000.0        -0.30
28 2026-02-11   96.17   97.63   95.66   96.65   43420.0         0.48
29 2026-02-12   95.84   97.80   91.42   92.16   71216.0        -3.68
30 2026-02-13   94.96   96.20   93.50   94.82   40301.0        -0.14
31 2026-02-16   98.49  101.26   96.95   99.50   85236.0         1.01
33 2026-02-18   96.96   98.53   95.38   96.22   92322.0        -0.74
34 2026-02-19   98.64   99.32   95.75   97.32   40699.0        -1.32
35 2026-01-22  103.28  106.28  102.27  105.21   84080.0         1.93
36 2026-02-23   97.22  100.49   96.23   99.35   98483.0         2.13
37 2026-02-24   93.89   95.72   92.27   94.85   40190.0         0.96
38 2026-02-25   91.70   92.28   89.47   90.94   50492.0        -0.76
39 2026-02-26   92.26   95.27   90.49   93.59   90132.0         1.33
40 2026-02-27   93.79   96.14   92.30   94.28   75743.0         0.49
41 2026-03-02   94.30   97.07   92.95   96.54  850000.0         2.24
42 2026-03-03   94.29   95.81   92.55   93.19   90336.0        -1.10
43 2026-03-04   93.95   94.90   92.54   93.59   92479.0        -0.36
45 2026-03-06   90.39   91.24   86.89   87.76   97471.0        -2.63
46 2026-03-09   89.76   92.53   87.80   90.65   66641.0         0.89
47 2026-02-06   98.04  100.96   97.53   99.98   72635.0         1.94
48 2026-03-11   92.68   95.36   90.84   92.99   72745.0         0.31
49 2026-03-12   89.71   90.49   88.09   89.54   95006.0        -0.17

In [18]:
df["Daily_Return"]=(df["Close"]-df["Open"]/df["Open"])*100

C:\Users\Dell\AppData\Local\Temp\ipykernel_15228\3311838851.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Daily_Return"]=(df["Close"]-df["Open"]/df["Open"])*100

In [19]:
df

,Date,Open,High,Low,Close,Volume,Price_Delta,Daily_Return
0,2026-01-02,101.09,103.37,100.08,102.04,89377.0,0.95,10104.0
1,2026-01-05,101.05,101.99,99.91,100.58,88404.0,-0.47,9958.0
2,2026-01-06,102.41,103.15,99.47,101.36,94045.0,-1.05,10036.0
3,2026-01-07,105.35,108.05,103.53,106.87,72352.0,1.52,10587.0
4,2026-01-08,105.13,109.88,104.24,107.49,79790.0,2.36,10649.0
5,2026-01-09,104.91,108.22,103.42,107.07,81919.0,2.16,10607.0
6,2026-01-12,107.95,109.49,104.84,106.57,45600.0,-1.38,10557.0
8,2026-01-14,108.89,111.08,107.60,109.85,67643.0,0.96,10885.0
9,2026-01-15,110.07,114.76,109.21,112.32,80764.0,2.25,11132.0
10,2026-01-16,109.43,111.85,108.13,108.77,49007.0,-0.66,10777.0
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,-0.07,10772.0
12,2026-01-20,109.43,110.92,105.67,107.52,96835.0,-1.91,10652.0
13,2026-01-21,106.18,107.28,102.64,104.09,77410.0,-2.09,10309.0
14,2026-01-22,103.28,106.28,102.27,105.21,84080.0,1.93,10421.0
15,2026-01-23,102.47,106.05,101.45,105.48,80447.0,3.01,10448.0
16,2026-01-26,100.84,102.72,99.25,101.00,48208.0,0.16,10000.0
17,2026-01-27,101.61,105.43,99.76,103.92,96491.0,2.31,10292.0
19,2026-01-29,97.83,98.89,95.17,96.84,58589.0,-0.99,9584.0
20,2026-01-09,104.91,108.22,103.42,107.07,81919.0,2.16,10607.0
21,2026-02-02,100.47,104.83,99.84,103.85,57453.0,3.38,10285.0
22,2026-02-03,100.79,101.81,100.05,101.02,76212.0,0.23,10002.0
23,2026-02-04,98.42,103.33,96.57,101.85,83525.0,3.43,10085.0
24,2026-02-05,97.64,100.11,91.29,92.70,87202.0,-4.94,9170.0
25,2026-02-06,98.04,100.96,97.53,99.98,72635.0,1.94,9898.0
26,2026-02-09,96.17,98.48,95.52,96.64,73828.0,0.47,9564.0
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,-0.30,9575.0
28,2026-02-11,96.17,97.63,95.66,96.65,43420.0,0.48,9565.0
29,2026-02-12,95.84,97.80,91.42,92.16,71216.0,-3.68,9116.0
30,2026-02-13,94.96,96.20,93.50,94.82,40301.0,-0.14,9382.0
31,2026-02-16,98.49,101.26,96.95,99.50,85236.0,1.01,9850.0
33,2026-02-18,96.96,98.53,95.38,96.22,92322.0,-0.74,9522.0
34,2026-02-19,98.64,99.32,95.75,97.32,40699.0,-1.32,9632.0
35,2026-01-22,103.28,106.28,102.27,105.21,84080.0,1.93,10421.0
36,2026-02-23,97.22,100.49,96.23,99.35,98483.0,2.13,9835.0
37,2026-02-24,93.89,95.72,92.27,94.85,40190.0,0.96,9385.0
38,2026-02-25,91.70,92.28,89.47,90.94,50492.0,-0.76,8994.0
39,2026-02-26,92.26,95.27,90.49,93.59,90132.0,1.33,9259.0
40,2026-02-27,93.79,96.14,92.30,94.28,75743.0,0.49,9328.0
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,2.24,9554.0
42,2026-03-03,94.29,95.81,92.55,93.19,90336.0,-1.10,9219.0
43,2026-03-04,93.95,94.90,92.54,93.59,92479.0,-0.36,9259.0
45,2026-03-06,90.39,91.24,86.89,87.76,97471.0,-2.63,8676.0
46,2026-03-09,89.76,92.53,87.80,90.65,66641.0,0.89,8965.0
47,2026-02-06,98.04,100.96,97.53,99.98,72635.0,1.94,9898.0
48,2026-03-11,92.68,95.36,90.84,92.99,72745.0,0.31,9199.0
49,2026-03-12,89.71,90.49,88.09,89.54,95006.0,-0.17,8854.0

In [20]:
df["Volume"].mean()

np.float64(111812.21739130435)

In [ ]:
df["Volume_MA_7"]=df["Volume"].rolling(7).mean()

In [ ]:
df

In [ ]:
volume_mean=df["Volume"].mean()

In [ ]:
volume_mean

In [ ]:
volume_std=df["Volume"].std()

In [ ]:
volume_std

In [ ]:
# analyse stock return distribution
mean_return=df["Daily_Return"].mean()
print("mean_return",mean_return)

variance_return=df["Daily_Return"].var()
print("variance_return",variance_return)

standard_return=df["Daily_Return"].std()
print("standard_return",standard_return)

In [15]:
df

         Date    Open    High     Low   Close    Volume
0  2026-01-02  101.09  103.37  100.08  102.04   89377.0
1  2026-01-05  101.05  101.99   99.91  100.58   88404.0
2  2026-01-06  102.41  103.15   99.47  101.36   94045.0
3  2026-01-07  105.35  108.05  103.53  106.87   72352.0
4  2026-01-08  105.13  109.88  104.24  107.49   79790.0
5  2026-01-09  104.91  108.22  103.42  107.07   81919.0
6  2026-01-12  107.95  109.49  104.84  106.57   45600.0
8  2026-01-14  108.89  111.08  107.60  109.85   67643.0
9  2026-01-15  110.07  114.76  109.21  112.32   80764.0
10 2026-01-16  109.43  111.85  108.13  108.77   49007.0
11 2026-01-19  108.79  109.79  106.87  108.72  450000.0
12 2026-01-20  109.43  110.92  105.67  107.52   96835.0
13 2026-01-21  106.18  107.28  102.64  104.09   77410.0
14 2026-01-22  103.28  106.28  102.27  105.21   84080.0
15 2026-01-23  102.47  106.05  101.45  105.48   80447.0
16 2026-01-26  100.84  102.72   99.25  101.00   48208.0
17 2026-01-27  101.61  105.43   99.76  103.92   96491.0
19 2026-01-29   97.83   98.89   95.17   96.84   58589.0
20 2026-01-09  104.91  108.22  103.42  107.07   81919.0
21 2026-02-02  100.47  104.83   99.84  103.85   57453.0
22 2026-02-03  100.79  101.81  100.05  101.02   76212.0
23 2026-02-04   98.42  103.33   96.57  101.85   83525.0
24 2026-02-05   97.64  100.11   91.29   92.70   87202.0
25 2026-02-06   98.04  100.96   97.53   99.98   72635.0
26 2026-02-09   96.17   98.48   95.52   96.64   73828.0
27 2026-02-10   97.05   99.07   95.25   96.75  620000.0
28 2026-02-11   96.17   97.63   95.66   96.65   43420.0
29 2026-02-12   95.84   97.80   91.42   92.16   71216.0
30 2026-02-13   94.96   96.20   93.50   94.82   40301.0
31 2026-02-16   98.49  101.26   96.95   99.50   85236.0
33 2026-02-18   96.96   98.53   95.38   96.22   92322.0
34 2026-02-19   98.64   99.32   95.75   97.32   40699.0
35 2026-01-22  103.28  106.28  102.27  105.21   84080.0
36 2026-02-23   97.22  100.49   96.23   99.35   98483.0
37 2026-02-24   93.89   95.72   92.27   94.85   40190.0
38 2026-02-25   91.70   92.28   89.47   90.94   50492.0
39 2026-02-26   92.26   95.27   90.49   93.59   90132.0
40 2026-02-27   93.79   96.14   92.30   94.28   75743.0
41 2026-03-02   94.30   97.07   92.95   96.54  850000.0
42 2026-03-03   94.29   95.81   92.55   93.19   90336.0
43 2026-03-04   93.95   94.90   92.54   93.59   92479.0
45 2026-03-06   90.39   91.24   86.89   87.76   97471.0
46 2026-03-09   89.76   92.53   87.80   90.65   66641.0
47 2026-02-06   98.04  100.96   97.53   99.98   72635.0
48 2026-03-11   92.68   95.36   90.84   92.99   72745.0
49 2026-03-12   89.71   90.49   88.09   89.54   95006.0